POST https://api.invertironline.com/token
Content-Type: application/x-www-form-urlencoded

username=lucas.ezequiel.321@gmail.com&password={password}&grant_type=password

###

GET https://api.invertironline.com/api/lucas.ezequiel.321@gmail.com/miportafolio
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6ImF0K2p3dCJ9.eyJzdWIiOiIyOTUwODIyIiwiSUQiOiIyOTUwODIyIiwianRpIjoiZThmODkwNmEtNDdkZS00M2FiLThlYjUtNmNlOGNhYzc5ODI3IiwiY29uc3VtZXJfdHlwZSI6IjEiLCJ0aWVuZV9jdWVudGEiOiJUcnVlIiwidGllbmVfcHJvZHVjdG9fYnVyc2F0aWwiOiJUcnVlIiwidGllbmVfcHJvZHVjdG9fYXBpIjoiVHJ1ZSIsInRpZW5lX1R5QyI6IlRydWUiLCJuYmYiOjE3MzY4MDUyOTIsImV4cCI6MTczNjgwNjE5MiwiaWF0IjoxNzM2ODA1MjkyLCJpc3MiOiJJT0xPYXV0aFNlcnZlciIsImF1ZCI6IklPTE9hdXRoU2VydmVyIn0.eo0d0sK0xA35cfXh_Mv1cKSsQkCiYRdUJYSCr8hlzi8thWipKDvKaVAn5FeN448vW3W_fSwUIRpV8CAJRJr6yQAKObnQpeopW2wRQVqOPK11zTXme5PM0V7wToxY86hjmU0H1hrWG3hMimcBqsCfVQXuOUZRZKoQHA-7g0QRGCKYaC90VVc1gOF2Uk2_Jx3AJxhLqmKezI5_Ay5SUqnL2KRhVlUh9YQ-71W7USqDBoVfchjDL9laRZJbkmdqsaonCCtjHR4-cnMHo9o49T33qaFJiYp9k1MAULGk61bOwAm6v_FAv5UYNQQqrpTheYeY_oy-ZOW8RZZn_Q1jz4S2Uw
